<?
$aMenuLinks = Array(
	Array(
		"ex2-1", 
		"/my/oldtasks/komsie-komsa/ex2-1/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-17", 
		"/my/oldtasks/komsie-komsa/ex2-17/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-18", 
		"/my/oldtasks/komsie-komsa/ex2-18/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-22", 
		"/my/oldtasks/komsie-komsa/ex2-22/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-23", 
		"/my/oldtasks/komsie-komsa/ex2-23/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-24", 
		"/my/oldtasks/komsie-komsa/ex2-24/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-25", 
		"/my/oldtasks/komsie-komsa/ex2-25/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-30", 
		"/my/oldtasks/komsie-komsa/ex2-30/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-31", 
		"/my/oldtasks/komsie-komsa/ex2-31/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ex2-ajax1", 
		"/my/oldtasks/komsie-komsa/ex2-ajax1/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Тест ajax", 
		"/my/oldtasks/komsie-komsa/test-ajax/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Мои новости", 
		"/my/oldtasks/komsie-komsa/moi-novosti/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Дерево ver.2", 
		"/my/oldtasks/komsie-komsa/derevo-ver-2/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Классификатор", 
		"/my/oldtasks/komsie-komsa/klassifikator/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Материалы ver. 1", 
		"/my/oldtasks/komsie-komsa/materialy-ver-1/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Материалы ver. 2", 
		"/my/oldtasks/komsie-komsa/materialy-ver-2/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Тестовая страница", 
		"/my/oldtasks/komsie-komsa/testovaya-stranitsa/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Разделы/элементы", 
		"/my/oldtasks/komsie-komsa/razdely-elementy/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Форма обратной связи", 
		"/my/oldtasks/komsie-komsa/feedback/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>